Huge review
- add/change variables to be more generic
- add all-mageia-docker as caller script
- make run-mageia more generic

diff --git a/mageia-docker b/mageia-docker
--- a/mageia-docker
+++ b/mageia-docker
@@ -5,26 +5,34 @@
 # Based on work done by Fedora and Juan Luis Baptiste
 # at https://github.com/juanluisbaptiste/docker-brew-mageia
 
+APPNAME=$(basename $0)
+
 # Workdirs
 if [ _"$HOME" = _"" ]; then
 	echo "Please define HOME to a sensible value"
 	exit -1
 fi
-GITDIR=$HOME/tmp/mageia-docker
-GITURL=https://github.com/myaccount
-OFFDIR=$HOME/tmp/official-images
-WORKDIR=$HOME/tmp
+
+# Get env var from the user home dir
+if [ -r $HOME/.$APPNAME ]; then
+	. $HOME/.$APPNAME
+fi
+
+GITDIRRO=${GITDIRRO:=$HOME/tmp/ro-$APPNAME}
+GITURLRO=${GITURL:=https://github.com/bcornec}
+TMPDM=$HOME/tmp/tmp-$APPNAME
 # By default we host ourselves
-MGAMODE="hosted"
-SCPURL=localhost:/tmp
-BIGURL=http://localhost/mageia-docker
+MGAMODE=${MGAMODE:="hosted"}
+SCPURL=${SCPURL:=localhost:/tmp}
+BIGURL=${BIGURL:=http://localhost/$APPNAME}
+MGAARCH=${MGAARCH:=x86_64}
+# Mirror to consider
+#MGAMIRROR=${MGAMIRROR:=http://distrib-coffee.ipsl.jussieu.fr/pub/linux/Mageia}
+
 
 # What is our current date
 DATE=`date "+%Y-%m-%d"`
 
-MGAARCH=x86_64
-
-APPNAME=$(basename $0)
 
 usage() {
 	echo >&2 "Syntax: $APPNAME [-v Mageia-Version][-m Mageia-Mirror-URL][-w /path/to/workdir]"
@@ -37,8 +45,11 @@ usage() {
 # Other value could be a number or cauldron
 if [ -r /etc/mageia-release ]; then
 	MGAVER=`pbdistrocheck | grep Ver: | cut -f2`
-	# Install deps in case they missing
-	sudo urpmi -q docker 1>/dev/null
+	rpm -q docker >& /dev/null
+	if [ $? -ne 0 ]; then
+		# Install deps in case they're missing
+		sudo urpmi docker
+	fi
 else
 	MGAVER=cauldron
 fi
@@ -58,7 +69,6 @@ FORCE="false"
 
 while true; do
         case "$1" in
-                -w|--workdir) WORKDIR=$2 ; shift 2 ;;
                 -v|--version) MGAVER="$2" ; shift 2 ;;
                 -m|--mirror) MGAMIRROR="$2" ; shift 2 ;;
                 -f|--force) FORCE="true" ; shift ;;
@@ -67,27 +77,16 @@ while true; do
         esac
 done
 
-# Accept CLI param to overwrite default version of Mageia
-if [ _"$MGAVER" = _"" ]; then
-	echo "Please provide a Mageia version such as with -v 5 e.g."
-	exit -1
-fi
-
 echo "Creating Mageia $MGAVER container on Docker Hub"
 
-# Reset mirror now we have the version, i case none was given
-if [ _"$MGAMIRROR" = _"" ]; then
-	MGAMIRROR="https://mirrors.mageia.org/api/mageia.$MGAVER.$MGAARCH.list"
-fi
-
-cd $GITDIR 2>&1 > /dev/null
+cd $GITDIRRO 2>&1 > /dev/null
 if [ $? -ne 0 ]; then
-	echo "$GITDIR doesn't exist, creating it"
-	mkdir -p $GITDIR
-	cd $GITDIR
-	git clone $GITURL/mageia-docker .
+	echo "$GITDIRRO doesn't exist, creating it"
+	mkdir -p $GITDIRRO
+	cd $GITDIRRO
+	git clone $GITURLRO/$APPNAME .
 	if [ $? -ne 0 ]; then
-		echo "Unable to clone $GITURL"
+		echo "Unable to clone $GITURLRO"
 		exit -1
 	fi
 fi
@@ -103,13 +102,7 @@ if [ $? -ne 0 ]; then
 	exit -1
 fi
 
-if [ _"$WORKDIR" != _"" ]; then
-	TARGETDIR="$WORKDIR/$MGAVER"
-else
-	echo "Work directory is an empty string"
-	exit -1
-fi
-
+TARGETDIR="$TMPDM/$MGAVER"
 echo "Cleanup $TARGETDIR first for idempotence"
 sudo rm -rf $TARGETDIR
 git rm --cached -r . 2>/dev/null 1>/dev/null
@@ -129,32 +122,37 @@ fi
 #
 if [ -d "$TARGETDIR/etc/sysconfig" ]; then
 	# allow networking init scripts inside the container to work without extra steps
-	echo 'NETWORKING=yes' > $WORKDIR/network
-	sudo install -m 644 $WORKDIR/network "$TARGETDIR"/etc/sysconfig/network
-	rm $WORKDIR/network
+	echo 'NETWORKING=yes' > $TMPDM/network
+	sudo install -m 0644 $TMPDM/network "$TARGETDIR"/etc/sysconfig/network
+	rm $TMPDM/network
 fi
 
 #
 # Docker mounts tmpfs at /dev and procfs at /proc so we can remove them
 sudo rm -rf "$TARGETDIR/dev" "$TARGETDIR/proc"
-sudo mkdir -p "$TARGETDIR/dev" "$TARGETDIR/proc"
+sudo install -m 0755 -p "$TARGETDIR/dev" "$TARGETDIR/proc"
+
+# Fix permissions for RPM system
+sudo chmod 644 "$TARGETDIR"/var/lib/rpm/[A-Z]* "$TARGETDIR"/var/lib/rpm/i*
 
 # make sure /etc/resolv.conf has something useful in it
-cat > $WORKDIR/resolv.conf << EOF
+cat > $TMPDM/resolv.conf << EOF
 nameserver 8.8.8.8
 nameserver 8.8.4.4
 EOF
-sudo install -m 644 $WORKDIR/resolv.conf "$TARGETDIR/etc/resolv.conf"
-rm $WORKDIR/resolv.conf
+sudo install -m 0644 $TMPDM/resolv.conf "$TARGETDIR/etc/resolv.conf"
+rm $TMPDM/resolv.conf
 
 # Needs root access for dev files e.g.
 echo "Capturing that chroot content into mageia-$MGAVER-$DATE.tar.xz"
 sudo rm -f mageia-$MGAVER-$DATE.tar.xz
 sudo tar -C $TARGETDIR -cJf mageia-$MGAVER-$DATE.tar.xz .
 sudo chmod 644 mageia-$MGAVER-$DATE.tar.xz
-sudo chroot $TARGETDIR rpm -qa | sort -u > $WORKDIR/rpm-qa
+sudo chroot $TARGETDIR rpm -qa | sort -u > $TMPDM/rpm-qa
+# Cleanup
+sudo rm -rf $TARGETDIR
 if [ -r $HOME/rpm-qa-$MGAVER ]; then
-	diff -q $HOME/rpm-qa-$MGAVER $WORKDIR/rpm-qa
+	diff -q $HOME/rpm-qa-$MGAVER $TMPDM/rpm-qa
 	if [ $? -eq 0 ]; then
 		echo "The list of RPMs packages didn't change so no need to build a new Docker image"
 		if [ $FORCE = "false" ]; then
@@ -163,8 +161,8 @@ if [ -r $HOME/rpm-qa-$MGAVER ]; then
 	fi
 fi
 
-cp $WORKDIR/rpm-qa $HOME/rpm-qa-$MGAVER
-cp $WORKDIR/rpm-qa rpm-qa-$MGAVER
+cp $TMPDM/rpm-qa $HOME/rpm-qa-$MGAVER
+cp $TMPDM/rpm-qa rpm-qa-$MGAVER
 
 echo "Creating the appropriate Docker file"
 cat > Dockerfile << EOF
@@ -196,16 +194,18 @@ if [ _"$MGAMODE" = _"hosted" ] || [ _"$MGAMODE" = _"local" ]; then
 		ssh $SSHHOST "mkdir -p $SSHDIR/$MGAVER ; rm -f $SSHDIR/$MGAVER/mageia-$DATE.tar.xz"
 		scp -p mageia-$MGAVER-$DATE.tar.xz $SCPURL/$MGAVER/mageia-$DATE.tar.xz
 	else
-		echo "Transferring the big file onto $SCPURL"
-		mkdir -p $SSHDIR/$MGAVER
-		sudo mv mageia-$MGAVER-$DATE.tar.xz $SSHDIR/$MGAVER/mageia-$DATE.tar.xz
+		if [ _"$KEEP" != _"0" ]; then
+			echo "Transferring the big file onto $SCPURL"
+			mkdir -p $SSHDIR/$MGAVER
+			sudo mv mageia-$MGAVER-$DATE.tar.xz $SSHDIR/$MGAVER/mageia-$DATE.tar.xz
+		fi
 	fi
 else
 	# We host on github
 
 	# Automatic build in Docker Hub does not support Git LFS yet
 	# Cf: https://github.com/docker/hub-feedback/issues/500
-	perl -pi -e "s|ADD mageia-$MGAVER-$DATE.tar.xz|ADD $GITURL/mageia-docker/$MGAVER/mageia-$DATE.tar.xz|" Dockerfile
+	perl -pi -e "s|ADD mageia-$MGAVER-$DATE.tar.xz|ADD $GITURLRO/$APPNAME/$MGAVER/mageia-$DATE.tar.xz|" Dockerfile
 
 	# This requires git-lfs for managing large files
 	sudo urpmi -q git-lfs 1>/dev/null
@@ -219,9 +219,12 @@ if [ -f mageia-$MGAVER-$DATE.tar.xz ]; then
 	sudo rm -f mageia-$MGAVER-$DATE.tar.xz
 fi
 
+if [ _"$MGAMODE" = _"local" ]; then
+	exit 0
+fi
 
 echo "Commiting into our git repo"
-git add Dockerfile mageia-docker LICENSE README.md run-mageia rpm-qa-$MGAVER
+git add Dockerfile $APPNAME LICENSE README.md run-mageia rpm-qa-$MGAVER
 git commit -m "update Mageia $MGAVER - $DATE"
 
 CID=`git show | head -1 | cut -d' ' -f2`
@@ -235,24 +238,18 @@ fi
 git push -f --set-upstream origin $MGAVER
 git checkout -f master
 # Backup rpm list for next run
-cp $WORKDIR/rpm-qa rpm-qa-$MGAVER
-cp $WORKDIR/rpm-qa $HOME/rpm-qa-$MGAVER
+cp $TMPDM/rpm-qa rpm-qa-$MGAVER
+cp $TMPDM/rpm-qa $HOME/rpm-qa-$MGAVER
 git add rpm-qa-$MGAVER
 git commit -m "update Mageia $MGAVER RPM list"
 git push
 
-# done in caller
-#rm -rf $WORKDIR
+# Doesn't seem to trigger a build with the webhook so forcing it
+curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "$MGAVER"}' -X POST https://registry.hub.docker.com/u/bcornec/mageia-docker/trigger/$DCKTRIG/
+
+rm -rf $TMPDM
 
 exit 0
-# Not sure wether it's still useful
-cd $OFFDIR/library 2>/dev/null 1>/dev/null
-if [ $? -ne 0 ]; then
-	echo "$OFFDIR doesn't exist, creating it"
-	mkdir -p $OFFDIR/library
-	cd $OFFDIR/library
-	git clone $GITURL/official-images .
-fi
 
 git remote update
 perl -pi -e 'undef $/; s|(/'$MGAVER'\nGitCommit:) [a-f0-9]+|$1 '$CID'|' mageia
