Try to fix automatic build in Docker Hub with LFS

diff --git a/mageia-docker b/mageia-docker
--- a/mageia-docker
+++ b/mageia-docker
@@ -78,7 +78,11 @@ if [ $? -ne 0 ]; then
 	echo "$GITDIR doesn't exist, creating it"
 	mkdir -p $GITDIR
 	cd $GITDIR
-	git clone https://github.com/bcornec/mageia-docker .
+	git clone $MGAURL .
+	if [ $? -ne 0 ]; then
+		echo "Unable to clone $MGAURL"
+		exit -1
+	fi
 fi
 git checkout master 2>/dev/null 1>/dev/null
 if [ $? -ne 0 ]; then
@@ -92,18 +96,6 @@ if [ $? -ne 0 ]; then
 	exit -1
 fi
 git rm --cached -r . 2>/dev/null 1>/dev/null
-
-echo "Creating the appropriate Docker file"
-cat > Dockerfile << EOF
-FROM scratch
-MAINTAINER bcornec@mageia.org
-ADD mageia-$MGAVER-$DATE.tar.xz /
-LABEL name="Mageia $MGAVER Base Image" \
-    vendor="Mageia" \
-    license="GPLv2" \
-    build-date="$DATE"
-CMD /bin/bash
-EOF
 
 TARGETDIR="$WORKDIR/$MGAVER"
 
@@ -140,21 +132,55 @@ echo "Capturing that chroot content into mageia-$MGAVER-$DATE.tar.xz"
 sudo rm -f mageia-$MGAVER-$DATE.tar.xz
 sudo tar -C $TARGETDIR -cJf mageia-$MGAVER-$DATE.tar.xz .
 sudo chmod 644 mageia-$MGAVER-$DATE.tar.xz
+sudo chroot $TARGETDIR rpm -aq > $WORKDIR/rpm-qa
+if [ -r rpm-qa-$MGAVER ]; then
+	diff -q rpm-qa-$MGAVER $WORKDIR/rpm-qa
+	if [ $? -eq 0 ]; then
+		echo "The list of RPMs packages didn't change so no need to build a new Docker image"
+		exit 1
+	fi
+fi
+
+cp $WORKDIR/rpm-qa rpm-qa-$MGAVER
+
+echo "Creating the appropriate Docker file"
+cat > Dockerfile << EOF
+FROM scratch
+MAINTAINER bcornec@mageia.org
+ADD mageia-$MGAVER-$DATE.tar.xz /
+LABEL name="Mageia $MGAVER Base Image" \
+    vendor="Mageia" \
+    license="GPLv2" \
+    build-date="$DATE"
+CMD /bin/bash
+EOF
 
 echo "Generating the docker image mageiaofficial:$MGAVER from it"
 docker build -t mageiaofficial:$MGAVER . 2>&1 >/dev/null
 docker images mageiaofficial:$MGAVER
+#docker tag mageiaofficial:$MGAVER bcornec/mageia:$MGAVER
+#docker login -u $MGAAC -p $MGAPWD
+#docker push bcornec/mageia:$MGAVER
+
+# Automatic build in Docker Hub do not support Git LFS yet
+# Cf: https://github.com/docker/hub-feedback/issues/500
+perl -pi -e 's|ADD mageia-|ADD $MGAURL/blob/$MGAVER/mageia-|' Dockerfile
 
 # This requires git-lfs for managing large files
 echo "Commiting into our git repo"
 git lfs track "*.tar.xz"
 git add .gitattributes
-git add mageia-$MGAVER-$DATE.tar.xz Dockerfile mageia-docker LICENSE README.md run-mageia
+git add mageia-$MGAVER-$DATE.tar.xz Dockerfile mageia-docker LICENSE README.md run-mageia rpm-qa-$MGAVER
 git commit -m "update Mageia $MGAVER - $DATE"
 CID=`git show | head -1 | cut -d' ' -f2`
 echo "New commit ID for latest commit is $CID"
 git push -f --set-upstream origin $MGAVER
 git checkout master
+# Backup rpm list for next run
+cp $WORKDIR/rpm-qa rpm-qa-$MGAVER
+git add rpm-qa-$MGAVER
+git commit -m "update Mageia $MGAVER RPM list"
+git push
 
 cd $OFFDIR/library
 if [ $? -ne 0 ]; then
